### ISSUE TITLE
Magenta cards are not found

### ISSUE THREAD

**Issue by cp2423** [sominator/multiplayer-card-project#2]
When playing the game the magenta cards do not appear... I think this is because in the preload function in game.js the filenames for the magenta cards use lowercase m  which is causing them not to be found since they use uppercase M in the actual filenames in the assets folder

**Comment by sominator** [comment]
Thanks for catching that!  I've updated the repo.  For some reason, the discrepancy doesn't throw an error on my machine.

**Comment by cp2423** [comment]
Resolved. BTW many thanks for making this tutorial really enjoyed working through it

**Comment by sominator** [comment]
Cheers!
